global:
  domain: argocd.local
configs:
  params:
    server.insecure: true
  cm:
    oidc.config: |
    name: Keycloak
    issuer: https://keycloak.192.168.49.2.nip.io/realms/develop
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    extraTls:
      - hosts:
        - argocd.local
        # Based on the ingress controller used secret might be optional
        secretName: wildcard-tls
