apiVersion: cert-manager.io/v1 
kind: ClusterIssuer
metadata: 
  name: selfsigned-cluster-issuer
spec: 
  selfSigned: {}

# You can create this via openssl x509
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: Root CA
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: certificates-issuer
spec:
  ca:
    secretName: root-secret
