grafana:
  enabled: true 
  
  # Administrative settings
  adminUser: admin
  adminPassword: prom-operator
  
  sidecar:
    datasources:
      url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/
  ingress:
    enabled: false
