# application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  labels:
    app: grafana
    environment: production
    team: monitoring
    
  finalizers:
   - resources-finalizer.argocd.argoproj.io
  
spec:
  project: default
  sources:
    - chart: prometheus-community/kube-prometheus-stack 
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 78.0.0
      helm:
        valueFiles:
          - $values/kube-prometheus-stack/values/default-values.yaml
    - repoURL: https://github.com/NazarSenchuk/argocd/
      targetRevision: HEAD
      ref: values
 
      
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m