---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-prod
  namespace: argocd
  annotations:

    argocd-image-updater.argoproj.io/image-list: prod=senchuknazar123/test-prod
    # 2. Use the alias for all subsequent configurations
    argocd-image-updater.argoproj.io/my_app.update-strategy: semver

    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: git@github.com:NazarSenchuk/argocd.git
    targetRevision: HEAD
    path: test-app/overlays/prod
  destination:  
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
